name: Firebase Deploy with Java Tests and Email Notification

on:
  push:
    branches:


jobs:
  build_test_deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java Environment
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Execute Java Tests
        run: |
          javac -d out src/*.java
          java -cp out org.junit.runner.JUnitCore YourTestClass

      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools


      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: firebase deploy --only hosting --token "$FIREBASE_TOKEN"


      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "✅ Firebase Deploy & Java Tests Completed"
          body: "Your Firebase deploy and Java tests ran successfully!"
          to: your-email@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
