name: Firebase Hosting Preview on PR

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  preview_deployment:

    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Build Step
        run: echo "Skipping build, no build needed."
      - name: Deploy Preview to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FIR_HOSTING_42D0A }}
          projectId: fir-hosting-42d0a
